// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Lw7xg4ziSL9H6mRm7586DK8KYpPLugM',
    appId: '1:995900970370:web:c52e247976028cbd5fab9b',
    messagingSenderId: '995900970370',
    projectId: 'yet-connect',
    authDomain: 'yet-connect.firebaseapp.com',
    storageBucket: 'yet-connect.firebasestorage.app',
    measurementId: 'G-ZXNWXQ236C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3NiTsajLf-zLqvxFSQ5w0e9ABXFUKZOI',
    appId: '1:995900970370:android:8d105a34e502aaba5fab9b',
    messagingSenderId: '995900970370',
    projectId: 'yet-connect',
    storageBucket: 'yet-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPk_7YXkuSVOUHZogK-Q7_zTDHqMrPbu0',
    appId: '1:995900970370:ios:4ba977edb41e10e45fab9b',
    messagingSenderId: '995900970370',
    projectId: 'yet-connect',
    storageBucket: 'yet-connect.firebasestorage.app',
    iosBundleId: 'com.yetchatplus.yetChatPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPk_7YXkuSVOUHZogK-Q7_zTDHqMrPbu0',
    appId: '1:995900970370:ios:4ba977edb41e10e45fab9b',
    messagingSenderId: '995900970370',
    projectId: 'yet-connect',
    storageBucket: 'yet-connect.firebasestorage.app',
    iosBundleId: 'com.yetchatplus.yetChatPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Lw7xg4ziSL9H6mRm7586DK8KYpPLugM',
    appId: '1:995900970370:web:6162141f0ead4d235fab9b',
    messagingSenderId: '995900970370',
    projectId: 'yet-connect',
    authDomain: 'yet-connect.firebaseapp.com',
    storageBucket: 'yet-connect.firebasestorage.app',
    measurementId: 'G-0LM9SPFEGK',
  );

}